Repository atish31/custom-input-types, pull requests merged in 2021-03, with the labels that each got.

#4 [HOTFIX] Pre-release fixes
  LICENSE.txt
  README.md
  src/index.js
Labels: bug, documentation

#5 Feat/pincode
  README.md
  index.html
  specs/custom-numerics/custom-numerics.spec.js
  src/index.js
  src/modules/custom-numerics/custom-numerics.js
Labels: documentation, enhancement, good first issue

#6 [Hotfix] phone
  specs/custom-numerics/custom-numerics.spec.js
  src/modules/custom-numerics/custom-numerics.js
Labels: bug

#7 Docs/GitHub pages
  docs/assets/npm-logo.png
  docs/index.css
  docs/index.html
Labels: documentation, enhancement, good first issue, help wanted
